package org.musadsl.musalce4bitwig;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.UUID;

import com.bitwig.extension.api.PlatformType;
import com.bitwig.extension.controller.AutoDetectionMidiPortNamesList;
import com.bitwig.extension.controller.ControllerExtensionDefinition;
import com.bitwig.extension.controller.api.ControllerHost;

public class MusaLCEforBitwigExtensionDefinition extends ControllerExtensionDefinition
{
   private static final UUID DRIVER_ID = UUID.fromString("2ec5ae8f-9196-4119-ac9d-42eb7c1d5329");

   /**
    * Cached version string, lazily resolved from the version.properties
    * file generated by the maven-antrun-plugin at build time (see pom.xml).
    * Resolved once at class load.
    */
   private static final String VERSION = loadVersion();

   public MusaLCEforBitwigExtensionDefinition()
   {
   }

   @Override
   public String getName()
   {
      return "MusaLCE";
   }

   @Override
   public String getAuthor()
   {
      return "yeste.studio";
   }

   @Override
   public String getVersion()
   {
      return VERSION;
   }

   /**
    * Read the project version from {@code version.properties} on the
    * classpath. The file is populated at build time from
    * {@code git describe --tags --always --dirty}; a leading {@code v}
    * (the convention used by tags in this repo: {@code v0.2}) is
    * stripped so the displayed version reads cleanly. Falls back to
    * {@code "0-dev"} when the file is missing — typical when running
    * from an IDE without going through Maven, or when git is not
    * available on the build host.
    */
   private static String loadVersion()
   {
      try (InputStream is = MusaLCEforBitwigExtensionDefinition.class.getResourceAsStream("/version.properties"))
      {
         if (is == null) return "0-dev";
         Properties props = new Properties();
         props.load(is);
         String v = props.getProperty("version");
         if (v == null || v.isBlank()) return "0-dev";
         v = v.trim();
         if (v.startsWith("v") || v.startsWith("V")) v = v.substring(1);
         return v;
      }
      catch (IOException e)
      {
         return "0-dev";
      }
   }

   @Override
   public UUID getId()
   {
      return DRIVER_ID;
   }
   
   @Override
   public String getHardwareVendor()
   {
      return "yeste.studio";
   }
   
   @Override
   public String getHardwareModel()
   {
      return "MusaLCE";
   }

   @Override
   public int getRequiredAPIVersion()
   {
      return 18;
   }

   @Override
   public int getNumMidiInPorts()
   {
      return 1;
   }

   @Override
   public int getNumMidiOutPorts()
   {
      return 0;
   }

   @Override
   public void listAutoDetectionMidiPortNames(final AutoDetectionMidiPortNamesList list, final PlatformType platformType)
   {
   }

   @Override
   public Controller createInstance(final ControllerHost host)
   {
      return new Controller(this, host);
   }
}
